# Generated by Django 3.1.4 on 2024-03-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_member_images/'),
        ),
    ]
