# Generated by Django 5.0.3 on 2024-03-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_teammember_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Leave', 'Leave'), ('Permission', 'Permission'), ('Personal Leave', 'Personal Leave'), ('Half-Day', 'Half-Day Leave'), ('Late', 'Late Check-in'), ('Force', 'Force Check-out')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
