# Generated by Django 5.0.3 on 2024-03-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('portal', '0003_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Pan_Number', models.CharField(max_length=100)),
                ('Aadhar_Number', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=100)),
            ],
        ),
    ]
