# Generated by Django 5.0.3 on 2024-03-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_checkinout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
