# Generated by Django 5.0.3 on 2024-03-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_rename_phone_number_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='checkinout_images/'),
        ),
    ]
